/*

 GAMEOVERSPLASH.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : P:\Google Drive\03 Design\Games\Gameboy\Splash.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GameOverSplashWidth 20
#define GameOverSplashHeight 18
#define GameOverSplashBank 0

extern unsigned char GameOverSplash[];

/* End of GAMEOVERSPLASH.H */
