/*

 IONICLIMBMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : P:\Google Drive\03 Design\Games\Gameboy\IonicLimb.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define IonicLimbMapWidth 20
#define IonicLimbMapHeight 18
#define IonicLimbMapBank 0

extern unsigned char IonicLimbMap[];

/* End of IONICLIMBMAP.H */
